### ISSUE TITLE
kernel 5.4 testing status

### ISSUE THREAD

**Issue by AmadeusGhost** [project-openwrt/openwrt#136]
* [ ] apm821xx
* [ ] archs38
* [ ] armvirt
* [ ] ath79: waited sync
* [x] bcm27xx: Run-tested-by: @SuLingGG
* [ ] gemini
* [ ] imx6
* [x] ipq40xx
* [ ] ipq806x: need tested, except that it can't be boot on a fool's device
* [ ] kirkwood
* [ ] lantiq
* [ ] malta
* [ ] mediatek
* [ ] mpc85xx
* [ ] mvebu
* [ ] mxs
* [ ] octeontx
* [ ] oxnas
* [ ] ramips: need tested, and successfully started on a gangster's mt7628 device
* [ ] sunxi
* [ ] tegra
* [x] x86
* [ ] zynq

**Comment by ElonH** [comment]
x86 kernel packages error:
* [ ] [ERROR: package/kernel/linux failed to build](https://github.com/project-openwrt/openwrt-isco/issues/643)
* [ ] [ERROR: package/kernel/mac80211 failed to build](https://github.com/project-openwrt/openwrt-isco/issues/640)
* [ ] [ERROR: package/kernel/ath10k-ct/regular failed to build](https://github.com/project-openwrt/openwrt-isco/issues/641)
* [ ] [ERROR: package/kernel/ath10k-ct/smallbuffers failed to build](https://github.com/project-openwrt/openwrt-isco/issues/642)
* [ ] [ERROR: package/feeds/packages/xtables-addons failed to build](https://github.com/project-openwrt/openwrt-isco/issues/644)
* [ ] [ERROR: package/ntlf9t/rtl8192du failed to build](https://github.com/project-openwrt/openwrt-isco/issues/645)
* [ ] [ERROR: package/kernel/mt76 failed to build](https://github.com/project-openwrt/openwrt-isco/issues/646)
* [ ] [ERROR: package/kernel/rtl8812au-ct failed to build](https://github.com/project-openwrt/openwrt-isco/issues/647)
* [ ] [ERROR: package/devel/perf failed to build](https://github.com/project-openwrt/openwrt-isco/issues/648)
* [ ] [ERROR: package/feeds/telephony/dahdi-linux failed to build](https://github.com/project-openwrt/openwrt-isco/issues/649)

**Comment by ElonH** [comment]
ipq40xx kernel packages error:
* [ ] [package/devel/perf](https://github.com/project-openwrt/openwrt-kisco/issues/13)

**Comment by ElonH** [comment]
ipq40xx kernel packages error:
* [ ] [package/lean/mt-drivers/mt_wifi](https://github.com/project-openwrt/openwrt-kisco/issues/15)

**Comment by AmadeusGhost** [comment]
> ipq40xx kernel packages error:
> 
> * [ ]  [package/lean/mt-drivers/mt_wifi](https://github.com/project-openwrt/openwrt-kisco/issues/15)

mtwfi can only be built on kernel 4.14 and below
